### ISSUE TITLE
JSON conversion

### ISSUE THREAD

**Issue by jcw** [arxpoetica/ss-angular-demo#3]
Looking at services.js, I have a question:

```
      if (message) {
        try {
          // broadcast with json payload
          json = JSON.parse(message);
          scope.$broadcast(name, message);
        } catch (err) {
          // broadcast with non-json payload
          scope.$broadcast(name, message);
        }
      } else {
```

As "json" isn't being used, is this just to test whether message is valid JSON? If so, why - both branches of the try do the same thing.

Small side-question: what is the "cache" member for, also in this file?

**Comment by davisford** [comment]
Good question...this is more of an artifact of a real-world service I was building that sometimes returned JSON, and sometimes returned objects, and sometimes didn't return anything, so I was trying to handle all cases.

This could be cleaned up.  The lesson here is that you need to define your own standard callback fn params and have client and server agree on them, and then stick to it.

So, in the server, when you do:

``` javascript

exports.actions = function (req, res, ss) {

   return {

       get: function (/* optional params here sent by client */ ) {

         /*
            what to return here?  standard node callback structure is
            function (err, response);

            res( ) will send back whatever arguments you pass it
            so long as client agrees on the arguments, you are good
          */

           // returning null for err (no error), 2nd param is object response
           return res(null, foos);

       }
};
```

The line where it parses the json and does not send it back in the callback is an error...it should parse it and return `scope.$broadcast(name, json)` 

I may try to clean this code up and make it a little more straightforward.

**Comment by jcw** [comment]
> it should parse it and return scope.$broadcast(name, json)

Perhaps it would be less confusing if the variable names "message" and "json" were reversed, i.e. parsing a JSON string into a JavaScript message object.
