### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jmvldz** [arxpoetica/ss-angular-demo#5]
I am assuming this code is free to use in other projects but it would be great if an explicit license were stated.

It is exactly what I was looking for in a SocketStream-Angular template. Thanks for your work!

**Comment by davisford** [comment]
I didn't put a license on it - so feel free to do whatever you wish with it.  If it makes people feel better, I can add a BSD license, but consider it public domain.

**Comment by jmvldz** [comment]
A BSD license would be more clear as public domain is not technically legal
in certain countries (e.g. Germany). Thanks for the quick response! I will
assume its PD and use it without worry for now then.

On Wed, Mar 13, 2013 at 6:28 PM, Davis Ford notifications@github.comwrote:

> I didn't put a license on it - so feel free to do whatever you wish with
> it. If it makes people feel better, I can add a BSD license, but consider
> it public domain.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/americanyak/ss-angular-demo/issues/5#issuecomment-14881723
> .

## 

Josh Valdez
Software Consultant
https://jmvldz.com

**Comment by davisford** [comment]
Added MIT license, it's just as permissive.

**Comment by jmvldz** [comment]
Thank you!
